# Generated by Django 3.1.2 on 2020-11-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.SmallIntegerField()),
                ('dob', models.DateField(null=True)),
                ('address', models.TextField(max_length=150)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_title', models.CharField(max_length=150)),
                ('Books_pages', models.SmallIntegerField()),
                ('pusbhish_date', models.DateField(auto_now_add=True)),
                ('Book_cost', models.IntegerField()),
                ('is_activate', models.BooleanField(default=True)),
                ('rating', models.SmallIntegerField()),
                ('auther_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.authors')),
            ],
        ),
    ]
