# Generated by Django 2.2.12 on 2020-11-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20201105_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.TextField(max_length=150)),
                ('gender', models.SmallIntegerField()),
                ('dob', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='auther_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Authors'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
