# Generated by Django 2.2.12 on 2020-11-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20201105_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
